### ISSUE TITLE
How to visualize the trajectory in the map

### ISSUE THREAD

**Issue by gmmhhh** [StanfordVL/iGibson#54] opened 2020-10-20 08:32 UTC
Hi, is there any way to generate the trajectory in the 2d room map?

**Comment by roberto-martinmartin** [comment] 2021-06-30 01:27
Duplicate of #41 https://github.com/StanfordVL/iGibson/issues/41
We are working on a tool to visualize the trajectories and will be available soon. We'll keep you posted!

**Closed by roberto-martinmartin** 2021-06-30 01:27 UTC
